# Generated by Django 2.2.28 on 2023-01-30 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='league',
            name='golf_course',
        ),
        migrations.AddField(
            model_name='league',
            name='golf_course',
            field=models.ManyToManyField(null=True, to='league.GolfCourse'),
        ),
    ]
