# Generated by Django 2.2.28 on 2023-02-03 07:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0002_auto_20230130_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='golf_course',
            field=models.ManyToManyField(blank=True, to='league.GolfCourse'),
        ),
        migrations.AlterField(
            model_name='league',
            name='users_joined',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
