# Generated by Django 2.2.28 on 2022-12-04 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stripeuserprofile',
            options={'verbose_name': 'Stripe User Profile', 'verbose_name_plural': 'Stripe User Profiles'},
        ),
    ]
