# Generated by Django 2.2.28 on 2023-02-06 10:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0003_gamescore'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamescore',
            name='given_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_given_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gamescore',
            name='putt',
            field=models.FloatField(null=True),
        ),
    ]
