# Generated by Django 2.2.28 on 2023-02-10 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20230206_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamescore',
            name='hole',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
