# Generated by Django 2.2 on 2023-02-24 09:27

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_auto_20230222_1106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamescore',
            name='score_data',
        ),
        migrations.RemoveField(
            model_name='gamescore',
            name='status',
        ),
        migrations.AddField(
            model_name='game',
            name='score_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='status',
            field=models.CharField(default='Playing', max_length=255, null=True),
        ),
    ]
