# Generated by Django 2.2.28 on 2022-07-20 12:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InviteFriend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('invited_email', models.EmailField(max_length=254)),
                ('from_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_invited_friend', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Invite Friend',
                'verbose_name_plural': 'Invite Friends',
            },
        ),
    ]
