# Generated by Django 2.2.28 on 2022-07-20 20:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invite_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitefriend',
            name='from_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_invited_friend', to=settings.AUTH_USER_MODEL),
        ),
    ]
