# Generated by Django 2.2.28 on 2022-12-04 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ghin',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='has_ghin',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
