# Generated by Django 2.2.28 on 2023-01-27 16:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20221204_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='friends',
            field=models.ManyToManyField(blank=True, null=True, related_name='user_friends', to=settings.AUTH_USER_MODEL),
        ),
    ]
